### ISSUE TITLE
build: can't build Linux application

### ISSUE THREAD

**Issue by itsyigid** [LucaCoduriV/Notiflut-Land#6]
Command `flutter build linux --release --verbose` fails with the following errors:

```
[  +10 ms] Unable to locate an Android SDK.
[   +4 ms] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +44 ms] Skipping pub get: version match.
[  +23 ms] Found plugin wayland_multi_window at
/home/yigid/.pub-cache/git/wayland_multi_window-8dd1d7016c1472dcc8531e91c52789d46c405e3c/
[   +6 ms] Found plugin window_manager at
/home/yigid/.pub-cache/git/window_manager-6f627e825db10d2f45bef0e0bbabdf5d1ecf1cb3/
[  +35 ms] Found plugin rinf at /home/yigid/.pub-cache/hosted/pub.dev/rinf-4.16.3/
[   +2 ms] Found plugin screen_retriever at
/home/yigid/.pub-cache/hosted/pub.dev/screen_retriever-0.1.9/
[  +23 ms] Found plugin wayland_multi_window at
/home/yigid/.pub-cache/git/wayland_multi_window-8dd1d7016c1472dcc8531e91c52789d46c405e3c/
[   +2 ms] Found plugin window_manager at
/home/yigid/.pub-cache/git/window_manager-6f627e825db10d2f45bef0e0bbabdf5d1ecf1cb3/
[  +34 ms] Found plugin rinf at /home/yigid/.pub-cache/hosted/pub.dev/rinf-4.16.3/
[   +1 ms] Found plugin screen_retriever at
/home/yigid/.pub-cache/hosted/pub.dev/screen_retriever-0.1.9/
[  +48 ms] Building Linux application...
[   +3 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/yigid/Notiflut-Land/notiflut_daemon/linux
[  +34 ms] -- Configuring done (0.0s)
[  +20 ms] -- Generating done (0.0s)
[        ] -- Build files have been written to:
/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release
[   +4 ms] executing: ninja -C build/linux/x64/release install
[   +7 ms] ninja: Entering directory `build/linux/x64/release'
[ +229 ms] [1/18] Generating libhub.so, _phony_
[   +2 ms] FAILED: plugins/rinf/libhub.so plugins/rinf/_phony_
/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins/rinf/libhub.so
/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins/rinf/_phony_
[  +19 ms] cd /home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins/rinf &&
/usr/bin/cmake -E env CARGOKIT_CMAKE=/usr/bin/cmake CARGOKIT_CONFIGURATION=Release
CARGOKIT_MANIFEST_DIR=/home/yigid/Notiflut-Land/notiflut_daemon/linux/../native/hub
CARGOKIT_TARGET_TEMP_DIR=/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins
/rinf/cargokit_build
CARGOKIT_OUTPUT_DIR=/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins/rinf
CARGOKIT_TARGET_PLATFORM=linux-x64
CARGOKIT_TOOL_TEMP_DIR=/home/yigid/Notiflut-Land/notiflut_daemon/build/linux/x64/release/plugins/r
inf/cargokit_build/tool CARGOKIT_ROOT_PROJECT_DIR=/home/yigid/Notiflut-Land/notiflut_daemon/linux
/home/yigid/.pub-cache/hosted/pub.dev/rinf-4.16.3/cargokit/run_build_tool.sh build-cmake
[   +1 ms] SEVERE:
================================================================================
[        ] SEVERE: Cargokit BuildTool failed with error:
[        ] SEVERE:
--------------------------------------------------------------------------------
[        ] SEVERE:  
[        ] SEVERE: rustup not found in PATH.
[        ] SEVERE:  
[        ] SEVERE: Maybe you need to install Rust? It only takes a minute:
[        ] SEVERE:  
[        ] SEVERE: $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
[        ] SEVERE:  
[        ] SEVERE:
================================================================================
[ +781 ms] [2/18] Generating
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_basic_message_c
hannel.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_binary_messenge
r.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_json_message_co
dec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_json_method_cod
ec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method_channel.
h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method_response
.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_plugin_registra
r.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry
.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_standard_messag
e_codec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_standard_method
_codec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/yigid/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/flutter_linux.h,
_phony_
[   +2 ms] [  +10 ms] Unable to locate an Android SDK.
[        ] [   +4 ms] executing: uname -m
[        ] [   +3 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping
update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [  +57 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +11 ms] Initializing file store
[        ] [  +12 ms] Done initializing file store
[        ] [  +49 ms] Skipping target: native_assets
[        ] [        ] Skipping target: gen_localizations
[        ] [        ] Skipping target: gen_dart_plugin_registrant
[        ] [ +145 ms] Skipping target: unpack_linux
[        ] [ +263 ms] Skipping target: kernel_snapshot
[        ] [  +28 ms] Skipping target: aot_elf_release
[        ] [  +23 ms] Skipping target: linux_aot_bundle
[        ] [  +23 ms] Skipping target: release_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [  +11 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 648ms.
[        ] [   +3 ms] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] ninja: build stopped: subcommand failed.
[   +8 ms] Building Linux application... (completed in 1,112ms)
[        ] "flutter linux" took 1,387ms.
[   +2 ms] Build process failed
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand
(package:flutter_tools/src/commands/build_linux.dart:89:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[   +1 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by LucaCoduriV** [comment]
Hi, to be honest it makes a long time that I am not working on it anymore.
But I'll try to compile it again and give you a feed back as soon as possible.

**Comment by itsyigid** [comment]
Thanks for the response. Can I fork it and maybe tinker a little bit then? I would like to give it my try because it looks promising from the screenshots.

**Comment by LucaCoduriV** [comment]
Certainly! If you find a solution, I would be very grateful if you could make a pull request to this repository.

**Comment by LucaCoduriV** [comment]
Hi, I wanted just to tell you that I will work on this project again really soon.
But I am not going to use flutter anymore.
Flutter was the main reason of why I stopped, I had to write a lot of boiler code to make things work and I had some limitation.

I found that I should be able to use Iced instead of flutter, so I am going to try to rewrite some code.

**Comment by itsyigid** [comment]
> Hi, I wanted just to tell you that I will work on this project again really soon. But I am not going to use flutter anymore. Flutter was the main reason of why I stopped, I had to write a lot of boiler code to make things work and I had some limitation.
> 
> I found that I should be able to use Iced instead of flutter, so I am going to try to rewrite some code.

I am so happy to hear that you'll work, and also work without Flutter :) We are using Flutter for an enterprise project, and tbh it was a horrible mistake.

The project is promising, the visuals are there, I want to support as far as I can, by using it in my daily driver and by contributing if it'll be in a language I use.
